### PR TITLE
Async is supported

### PR DESCRIPTION
**Pull request by Pure-Peace**
**PR** - rosu-pp v0.1.2
- Suppot asynchronous beatmap file reading and parsing (based on async-std).
- New features "async_std" (optional).
- Add an asynchronous wrapper for `calculate()`: `calculate_async()`.
- Add asynchronous testing.
- README.md added async examples.
- Change the version number to 0.1.2.
- Added async keywords in Cargo.toml

### CODE REVIEW

**Comment by MaxOhn** [comment]
Thanks for the PR!
Looks pretty good. I think the code duplication can be reduced a little through some `#[cfg]`s but I'll look into it.
Merging it right up :)

FYI I want to keep the `main` branch in sync with the version on crates.io so the new stuff goes into the `next` branch but you couldn't know that so no condemning here.

**Comment by Pure-Peace** [comment]
Oh, I agree with you. Really good project! :D

**Comment by MaxOhn** [comment]
Small update:

I removed the `calculate_async` pp methods since they don't benefit from asynchronocity and if people need them async they can just wrap them in an `async { ... }.await`.

Async map parsing is super worth it though so that was a great addition.
Also added an `async_tokio` feature so there's an option between `async_std` and `tokio` runtimes.

I'll let it run in some application for a few days to check if everything's working fine and then publish it as v0.2.0. 😃

**Comment by Pure-Peace** [comment]
❤️Nice!

**Pull request merged**
